feat: ✨  a07
mami-tus/AtCoder pull request #107
Opened 2023-02-12 12:06 UTC by mami-tus

- [A07 - Event Attendance](https://atcoder.jp/contests/tessoku-book/tasks/tessoku_book_g)

1次元の累積和の問題を解きました
前日比の累積和を計算することで各日の出席日数が求められました

2023-02-12 12:10 UTC, mami-tus commented on A07/a07.py
> +    ans[d] = ans[d - 1] + day_before_last[d]
この計算でインデックス外にならないように`day_before_last`と`ans`は最初と最後に0を追加して初期化

2023-02-13 01:59 UTC, shunya-tanaka-512 requested changes

2023-02-13 01:59 UTC, shunya-tanaka-512 commented on A07/a07.py
> +    ans[d] = ans[d - 1] + day_before_last[d]
そもそもansを配列で持つ必要なくない？

2023-02-26 13:41 UTC, mami-tus commented on A07/a07.py
> +    ans[d] = ans[d - 1] + day_before_last[d]
修正しました

2023-02-27 01:09 UTC, shunya-tanaka-512 approved these changes

2023-04-15 13:18 UTC, merged