feat: ✨  a08
mami-tus/AtCoder pull request #108
Opened 2023-02-12 12:24 UTC by mami-tus

- [A08 - Two Dimensional Sum](https://atcoder.jp/contests/tessoku-book/tasks/tessoku_book_h)

二次元累積和の問題を解きました。
縦方向の累積和をとってから横方向の累積和を取ることで二次元累積和を求めました
長方形領域は右下の(c,d) - (a-1, d) - (c, b-1) + (a-1, b-1)で求めました

2023-02-13 02:48 UTC, shunya-tanaka-512 requested changes

2023-02-13 02:48 UTC, shunya-tanaka-512 commented on A08/a08.py
> +queries = [list(map(int, input().split())) for _ in range(q)]
せっかく計算量を少なくしようとしてるんだから、こういうところも。
queriesは最後にprintするところ以外で使うことないからリスト化してメモリに持つ必要ないよね？

2023-02-26 13:42 UTC, mami-tus commented on A08/a08.py
> +queries = [list(map(int, input().split())) for _ in range(q)]
修正しました

2023-02-27 01:10 UTC, shunya-tanaka-512 approved these changes

2023-04-15 13:18 UTC, merged