ABC274B
mami-tus/AtCoder pull request #72
Opened 2022-10-23 13:05 UTC by mami-tus

2次元リストをインデックスごとに取り出して、#の数を数えました。

2022-10-31 02:14 UTC, shunya-tanaka-512 requested changes

2022-10-31 02:14 UTC, shunya-tanaka-512 commented on ABC274B/abc274b.py
> +    column = [i[j] for i in C]
jとiが逆
jを先に使うのが気持ち悪い

2022-10-31 02:14 UTC, shunya-tanaka-512 commented on ABC274B/abc274b.py
> +    column = [i[j] for i in C]
数えるだけならわざわざリスト内包表記でリストに取り出す意味がない
Generator等でメモリ効率をあげよう

2022-11-06 13:10 UTC, mami-tus commented on ABC274B/abc274b.py
> +C = (list(input()) for _ in range(H))
@shunya-tanaka-512 
ここをジェネレータ式にして一度取り出すごとに数を数えるようにしました

2022-11-06 13:11 UTC, mami-tus commented on ABC274B/abc274b.py
> +    column = [i[j] for i in C]
修正しました

2022-11-06 13:11 UTC, mami-tus commented on ABC274B/abc274b.py
> +    column = [i[j] for i in C]
修正しました

2022-11-07 00:31 UTC, shunya-tanaka-512 approved these changes

2022-11-13 01:08 UTC, merged