ABC275D
mami-tus/AtCoder pull request #75
Opened 2022-10-30 14:54 UTC by mami-tus

TLEになりましたが、問題文通りに関数を定義して解きました。

2022-10-31 03:22 UTC, shunya-tanaka-512 requested changes
メモ化再帰というめちゃくちゃよくあるパターンで、これは業務上も使いうるので解説をよく読んで今回の解法の理解をするとともに、メモ化再帰について調べて類似問題が何度もAtCoderに出ているので過去問から漁って解いてください

2022-10-31 03:27 UTC, shunya-tanaka-512 commented
解説だとlru_cacheという標準モジュールにあるデコレータを使ってめちゃくちゃ簡単にメモ化を実装してるけど、もちろんこれはこれで使い方は知っておいた上で、メモ化のロジックそのものを調べてlru_cacheを使わずに実装してみてほしい。
ヒントだけ伝えておくと、名前の通りメモを残す。
・0を渡したときは1が返ってくる
・1を渡したときはxが返ってくる
・・・
みたいにメモ配列を用意してそこに一度計算したものは保存していくというもの

2022-11-06 15:01 UTC, mami-tus commented
すでに計算したものはmemoのdictから取り出すことでACになりました

2022-11-07 00:34 UTC, shunya-tanaka-512 approved these changes

2022-11-13 01:09 UTC, merged