ABC276B
mami-tus/AtCoder pull request #77
Opened 2022-11-06 16:07 UTC by mami-tus

空の２次元リストを定義し結ばれた都市を入れていき、後でsortedでソートしてACしました。

2022-11-07 01:00 UTC, shunya-tanaka-512 requested changes
Cityクラスを作ってもっと意味がわかるコードにする

2022-11-13 12:49 UTC, mami-tus commented
実行時間が20秒ほどかかりTLEしてしまいましたがClassを作成して実装しました

2022-11-14 01:08 UTC, shunya-tanaka-512 requested changes
なんか違う。
Cityクラスのプロパティは
・自身の番号
・繋がってるCityの配列

2022-11-20 14:58 UTC, mami-tus commented
クラス構造を修正するとACしました

2022-11-21 00:24 UTC, shunya-tanaka-512 requested changes

2022-11-21 00:24 UTC, shunya-tanaka-512 commented on ABC276B/abc276b.py
> +    city_a.connected_cities.append(city_b.num)
オブジェクト指向的に言えばこうやってクラスのプロパティを直接触ってるのはNGで、
Cityクラスに
```py
def add_connected_city(self, city_no):
    self.connected_cities.append(city_no)
```
みたいなメソッドを追加して外からはこれを呼ぶべき

2022-11-27 08:37 UTC, mami-tus commented on ABC276B/abc276b.py
> +    city_a.connected_cities.append(city_b.num)
修正しました

2022-11-27 11:34 UTC, shunya-tanaka-512 approved these changes

2022-11-27 11:34 UTC, merged