ABC277B
mami-tus/AtCoder pull request #80
Opened 2022-11-13 13:12 UTC by mami-tus

Cardクラスを作成し、トランプであるかどうか調べるインスタンスメソッドや、重複してるカードがないかのif文で条件を満たしているかどうかを判定しました。

2022-11-14 01:13 UTC, shunya-tanaka-512 requested changes

2022-11-14 01:13 UTC, shunya-tanaka-512 commented on ABC277B/abc277b.py
> +playing_cards_nums = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K"]
これはCardクラス内の定数にするべき

2022-11-20 14:58 UTC, mami-tus commented on ABC277B/abc277b.py
> +playing_cards_nums = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K"]
修正しました

2022-11-21 00:25 UTC, shunya-tanaka-512 approved these changes

2022-11-22 13:50 UTC, merged