ABC278B
mami-tus/AtCoder pull request #82
Opened 2022-11-20 03:46 UTC by mami-tus

datetimeモジュールを使い、Clockクラスを作成しました。
timeオブジェクトだとtimedeltaオブジェクト使用できなかったので、任意の日付を入れてdatetimeオブジェクトにしています。

2022-11-21 05:22 UTC, shunya-tanaka-512 requested changes

2022-11-21 05:22 UTC, shunya-tanaka-512 commented on ABC278B/abc278b.py
> +import datetime
datetimeをimportするときは
```py
from datetime import datetime
```
にしよう。
じゃないとdatetime.datetimeって書かないといけなくなって可読性が悪くなる

2022-11-21 05:22 UTC, shunya-tanaka-512 commented on ABC278B/abc278b.py
> +        clock.time += datetime.timedelta(minutes=1)
1分おきに全部調べるのは調べすぎ。
例えば 1600 の場合、
2番目と3番目を入れ替えると
1060とかになってこのまま16時台では絶対にTrueになりえない。
2番目の数字は0〜5じゃないといけないから。

ちなみに1600が入力値の場合の答えは2000になるわけだけど、
1分おきに調べる方法だと240回も無駄に調べてることになる。

2022-11-27 08:41 UTC, mami-tus commented on ABC278B/abc278b.py
> +        clock.time += datetime.timedelta(minutes=1)
clock.time.hourが6〜8、16〜8だったら1時間おきに調べるようにしました

2022-11-27 11:37 UTC, shunya-tanaka-512 approved these changes

2022-11-27 11:37 UTC, merged