ABC278C
mami-tus/AtCoder pull request #83
Opened 2022-11-20 03:49 UTC by mami-tus

TLEしましたが、ユーザ番号と、フォロワーのリストがプロパティのTwidaiUserクラスを作成し、条件をif文で実装しました。

2022-11-21 05:27 UTC, shunya-tanaka-512 requested changes
follower（フォロワー）は自分のことをフォローしてる人を指す言葉だから逆の意味になっちゃってる。
自分がフォローしてる人という変数ならfollowing_usersとかの方がいい。

2022-11-21 05:30 UTC, shunya-tanaka-512 requested changes
この手の要件はlistじゃなくてsetを使おう

2022-11-27 08:42 UTC, mami-tus commented
setにしました

2022-11-27 11:39 UTC, shunya-tanaka-512 approved these changes

2022-11-27 11:39 UTC, merged