ABC280A
mami-tus/AtCoder pull request #87
Opened 2022-12-04 14:13 UTC by mami-tus

二重ループで時間内でACしました。

2022-12-05 01:21 UTC, shunya-tanaka-512 requested changes
count使って二重ループ避けられるはず

2022-12-11 15:35 UTC, mami-tus commented
count使いました

2022-12-12 00:45 UTC, shunya-tanaka-512 approved these changes

2022-12-12 00:46 UTC, shunya-tanaka-512 requested changes

2022-12-12 00:46 UTC, shunya-tanaka-512 commented on ABC280A/abc280a.py
> +    count += i.count("#")
mapとsumでforすらいらなくなる

2022-12-18 15:10 UTC, mami-tus commented on ABC280A/abc280a.py
> +    count += i.count("#")
修正しました

2022-12-19 00:47 UTC, shunya-tanaka-512 approved these changes

2022-12-24 14:03 UTC, merged